### ISSUE TITLE
新版 - 订阅折扣活动（主题、行为）

### ISSUE THREAD

**Issue by itwangxiang** [bookey-dev/bookey.requirement#193]
### 描述

展示对象：登录且非 VIP 用户

展示途径：

1. `Banner`
2. `折扣图标`  -（手托）
   - 固定在 discover 页
   - 固定在 challenge 页
   - 固定在 library 页
   - 固定在 me 页

展示逻辑：通过 [currentEvent](https://dev.bookey.app:8081/swagger-ui.html#/event-controller) api 获取活动信息

> 1. 前端 APP 如果没有开发对应的折扣活动界面时，不展示该活动
> 2. 行为活动，取消倒计时操作(即不调用 [joinCurrentEvent](https://dev.bookey.app:8081/swagger-ui.html#/event-controller) api)

- 当有主题活动时，`Banner`  和 `折扣图标` 都要展示，点击进入主题活动页面
   - 当主题折扣活动时，Banner 取消轮播 
   - 当未配置 bannerImg, 则不在 `Banner` 上展示，启用轮播
- 当有行为活动时， 只在 `折扣图标` 展示 ， `Banner` 不再展示，点击进入行为活动页面

### 备注

1、未登录状态下，不展示折扣入口图标。
2、用户通过任何渠道获得VIP权限后，折扣入口图标消失。
3、其次折扣入口展示的依据是看后台是否打开折扣开关，若后台打开折扣开关，对应应该展示的用户就展示，若后台关闭折扣开关，则所有用户不展示。
4、新用户打开APP，完成Boarding后，若未选择7天试用，进入主界面后即刻出现折扣入口图标。
5、当前版本暂无5折主题活动界面，故不考虑5折的主题活动。
## 任务

- [x] UI
- [x] IOS
- [ ] Android

**Comment by Johnsonkk2020** [comment]
根据目前数据反映，用户基本在15天内完成折扣订阅、年度订阅。所以折扣展示在后期优化时可展示15天倒计时。
